### ISSUE TITLE
"Undefined index: category" when trying to send test post

### ISSUE THREAD

**Issue by voxpelli** [aaronpk/OwnYourGram#11]
I'm getting this error when I'm trying to send a test post after I've authorized myself using `kodfabrik.se`:

```
Slim Application Error

The application could not run because of the following error:
Details
Type: ErrorException
Code: 8
Message: Undefined index: category
File: /web/sites/ownyourgram.com/lib/helpers.php
Line: 99
Trace

#0 /web/sites/ownyourgram.com/lib/helpers.php(99): Slim\Slim::handleErrors(8, 'Undefined index...', '/web/sites/owny...', 99, Array)
#1 /web/sites/ownyourgram.com/controllers/controllers.php(153): micropub_post('http://micropub...', 'eyJ0eXAiOiJKV1Q...', Array, '/tmp/igD2Qmej.j...')
#2 [internal function]: {closure}()
#3 /web/sites/ownyourgram.com/vendor/slim/slim/Slim/Router.php(172): call_user_func_array(Object(Closure), Array)
#4 /web/sites/ownyourgram.com/vendor/slim/slim/Slim/Slim.php(1222): Slim\Router->dispatch(Object(Slim\Route))
#5 /web/sites/ownyourgram.com/vendor/slim/slim/Slim/Middleware/Flash.php(86): Slim\Slim->call()
#6 /web/sites/ownyourgram.com/vendor/slim/slim/Slim/Middleware/MethodOverride.php(94): Slim\Middleware\Flash->call()
#7 /web/sites/ownyourgram.com/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#8 /web/sites/ownyourgram.com/vendor/slim/slim/Slim/Slim.php(1174): Slim\Middleware\PrettyExceptions->call()
#9 /web/sites/ownyourgram.com/public/index.php(24): Slim\Slim->run()
#10 {main}
```

**Comment by aaronpk** [comment]
Thanks for catching this! It was a problem if the test photo didn't have any tags.
